version: '3.9'

services:
  invoicechecker-frontend:
    container_name: invoicechecker-frontend
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - invoicechecker-backend
    restart: always

  invoicechecker-backend:
    container_name: invoicechecker-backend
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
