version: '3.9'

services:
  invoicechecker-frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: always

  invoicechecker-backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
